version: '3'
services:
  load-balancer:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: load-balancer
    restart: unless-stopped
    tty: true
    ports:
      - "9090:9090"
  service1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service1
  service2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service2
  service3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service3